first commit
userkgrf/go_final_project pull request #1
Opened 2024-07-20 12:48 UTC by userkgrf

2024-07-21 09:47 UTC, just-musha requested changes
Привет! 
Хорошо, что есть описание проекта, и тесты проходят :+1: 

В первой итерации предлагаю поправить один момент, связанный с работой с базой, использую имеющиеся у тебя знания. Это поможет чуть лучше структурировать код и разгрузить хендлеры, где сейчас очень много всего происходит. Ну и файлы переименовать будет полезно. Для первой итерации это все.

2024-07-21 09:47 UTC, just-musha commented on identifier.sqlite
Этот файл не нужно добавлять в репозиторий

2024-07-21 09:47 UTC, just-musha commented on .idea/.gitignore
Папку `.idea` не нужно добавлять в репозиторий. Давай её удалим из пул реквеста

2024-07-21 09:47 UTC, just-musha commented on step2.go
> +func workDb(appPath string) {
@userkgrf этот файл нужен ? Если да - нужно раскоментировать. Если нет - лучше удалить

2024-07-21 09:47 UTC, just-musha commented on step3.go
Для файлов проекта вместо step.go - лучше выбрать более понятные названия, отражающие что в файле. Это программа минимум

2024-07-21 09:47 UTC, just-musha commented on step3.go
А ещё лучше будет - поработать над структурой проекта и вынести хендлеры и работу с базой в отдельные пакеты.

Пример организации проекта можешь посмотреть здесь например: https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10

2024-07-21 09:47 UTC, just-musha commented on step4.go
> +	db, err := sql.Open("sqlite3", "./scheduler.db")
Важный момент - сейчас ты открываешь соединение с БД в каждом хендлере, по сути - на каждый запрос. Это очень дорого. Посмотри в задании 8 спринта как релизован репозиторий, и давай здесь применим этот подход. Создать коннекшн нужно один раз и положить в структуру Repository.
А методы для работы с ним - вынести в отедльный пакет (как это сделано в 8 спринте)

2024-07-21 09:47 UTC, just-musha commented on step4.go
> +	db, err := sql.Open("sqlite3", "./scheduler.db")
Нужно это обязательно поправить, и поправить все хендлеры, чтобы они не работали с базой напрямую, а делали вызов метода Repository.

2024-07-22 11:28 UTC, just-musha requested changes
Отлично! Лучше! Ещё пару коментов по структуре отписала, часть на твоем усмотрение.

По стилю - обрати внимание на обработку ошибок. Где-то оставила комент, но тебе нужно найти все места, и добавить обработку.

2024-07-22 11:28 UTC, just-musha commented on repository/repository.go
> +func (r *Repository) GetTasks(date time.Time, limit int) ([]map[string]string, error) {
А может здесь вернуть слайс задач?

Мапа здесь выглядит как дополнительное усложнение. Если можно проще - лучше проще

2024-07-22 11:28 UTC, just-musha commented on repository/repository.go
> +		task := map[string]string{
Вот тут очень хочется упростить, чтобы это была стркутурка Task (см. предыдущий комент)

2024-07-22 11:28 UTC, just-musha commented on repository/repository.go
> +func (r *Repository) MarkTaskDone(id int64) error {
Это больше похоже на хендлер. Оно вызывает уже несколько запросов к БД, и по идее на уровне Repository такого быть не должно - тк репозиторий это по сути обертка над запросами. 

Требовать не буду, но если есть желание - можешь вынести на уровень выше, и запросы заменить на методы репозитория, как и в хендлерах. Это будет логичне.

2024-07-22 11:28 UTC, just-musha commented on repository/repository.go
> +func (r *Repository) MarkTaskDone(id int64) error {
Ещё бывает что выделают 3 слоя (репозиторий, сервис и хендлер) -  https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10

В задании достаточно двух как у тебя сейчас.

2024-07-22 11:28 UTC, just-musha commented on handlers.go
> +package main
Хендлеры тоже будет здорово в отдельный пакет собрать (но это уже по твоему желанию)

2024-07-22 11:28 UTC, just-musha commented on main.go
> +var repo *repository.Repository
Лучше завести струкуру Handler, и этот указатель положить внутрь. А все хендлры сделать методами этой стркутуры. Тогда у них будет доступ к этому указателю и глобальная переменная будет не нужна (это плохая практика использвоать глобальные переменные)

2024-07-22 11:28 UTC, just-musha commented on handlers.go
> +		} /*else {
Закоментированный код лучше удалить, чтоб код оставался чистым

2024-07-22 11:28 UTC, just-musha commented on handlers.go
> +		_, err = time.Parse("20060102", dateStr)
Шаблон для времени - лучше вынести в константу наверх, много где используется

2024-07-22 11:28 UTC, just-musha commented on handlers.go
> +	json.NewEncoder(w).Encode(map[string]interface{}{"tasks": tasks})
Тут нужно проверить и обработать ошибку явно. И в других местах ниже по коду где есть этот метод

Ошибки принято явно проверять и что-то с ними делать

2024-07-22 11:28 UTC, just-musha commented on handlers.go
> +	tasks, err := repo.GetTasks(date, 50)
Число лучше вынести наверх в константу с понятным названием

2024-07-22 11:28 UTC, just-musha commented on handlers.go
> +	json.NewEncoder(w).Encode(map[string]interface{}{})
Проверить ошибку

2024-07-22 11:28 UTC, just-musha commented on handlers.go
> +	json.NewEncoder(w).Encode(map[string]interface{}{})
Проверить ошибку

2024-07-22 11:28 UTC, just-musha commented on handlers.go
> +	json.NewEncoder(w).Encode(map[string]interface{}{
Проверить ошибку

2024-07-22 11:28 UTC, just-musha commented on handlers.go
> +	json.NewEncoder(w).Encode(map[string]interface{}{"error": message})
Проверить ошибку

2024-07-22 11:28 UTC, just-musha commented on handlers.go
> +	json.NewEncoder(w).Encode(repository.Response{Error: err})
Проверить ошибку

2024-07-22 11:28 UTC, just-musha commented on handlers.go
> +	json.NewEncoder(w).Encode(map[string]interface{}{
Проверить ошибку

2024-07-22 11:28 UTC, just-musha commented on main.go
> +	fmt.Printf("Server started successfully. Port: %s\n", port)
:+1: хорошо что есть сообщиение в консоли что сервис поднялся, понятно что происходит

2024-07-22 11:28 UTC, just-musha commented on repository/nextDate.go
> +func NextDate(now time.Time, date string, repeat string) (string, error) {
Этот метод будет логично вынести на уровень выше. Он не является методом репозитория, и не имеет к нему отношения

2024-07-22 11:28 UTC, just-musha commented on repository/repository.go
> +	_ "github.com/mattn/go-sqlite3"
Сортировка импортов - нужно разбить на блоки - стандартные пакеты, потом блок внеших, и потом отдельно внутренние пакеты (если есть)

Это нужно пройтись по всем файлам и проверить и поправить

2024-07-22 11:28 UTC, just-musha commented on repository/repository.go
> +type Response struct {
Кажется это долждно быть уровнем выше, ближе к хендлерам. Репозиторий не должден инчего знать про респонс и апи

2024-07-23 10:58 UTC, just-musha requested changes
По структуре - топ! Остались не большие правки, в основном связанные с упрощением кода. И работа будет принята.

2024-07-23 10:58 UTC, just-musha commented on handlers/handlers.go
> +	w.WriteHeader(http.StatusNoContent)
Здесь не  200 нужен статус?

2024-07-23 10:58 UTC, just-musha commented on handlers/handlers.go
> +	Repo *repository.Repository
:+1: то что нужно

2024-07-23 10:58 UTC, just-musha commented on handlers/handlers.go
> +	if err := json.NewEncoder(w).Encode(Response{Error: err}); err != nil {
Как насчет тут упростить и сразу вернуть ошибку  `http.Error(w, "Error writing error response: "+err.Error(), http.StatusInternalServerError)` ?

2024-07-23 10:58 UTC, just-musha commented on handlers/handlers.go
> +	if err := json.NewEncoder(w).Encode(Response{Error: err}); err != nil {
(ну и  ещё предложение err не возвращать клиенту тк это может быть не безопасно для internal server error. лучше просто его залогировать)

2024-07-23 10:58 UTC, just-musha commented on handlers/handlers.go
> +		sendErrorResponse(w, "Error writing JSON response: "+err.Error())
Тут достаточно залогировать ошибку

2024-07-23 10:58 UTC, just-musha commented on repository/repository.go
> +		tasks = []Task{}
А этот кейс `tasks == nil` кстати для чего нужен? Можно ли его убрать, для простоты?

2024-07-23 10:58 UTC, just-musha commented on handlers/handlers.go
> +			http.Error(w, "Error writing response: "+err.Error(), http.StatusInternalServerError)
Тут достаточно просто залогировать

2024-07-23 11:46 UTC, userkgrf commented on repository/repository.go
> +		tasks = []Task{}
Тесты не проходят, если убрать этот кейс . Вылетает ошибка: `Error: Expected value not to be nil.`

2024-07-23 11:49 UTC, merged

2024-07-23 13:25 UTC, just-musha commented
@userkgrf поторопился мержить немного

2024-07-23 13:27 UTC, just-musha commented
@userkgrf если что приницип такой: все изменения должнны быть в одном ПР,
и пока нет Approove - мержить не нужно.

Это на будущее уже, получается.

2024-07-23 13:28 UTC, userkgrf commented
Я и сам не заметил, как это получилось((

2024-07-23 13:28 UTC, userkgrf commented
> @userkgrf поторопился мержить немного

Я и сам не заметил, как это получилось((